version: '3.3'

services:
  finances_database:
    image: postgres:11-alpine
    container_name: finances_database
    environment:
      - POSTGRES_USER=finances_root
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=finances
    volumes:
      - finances_database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - finances_network

  finances_backend:
    build: .
    container_name: finances_backend
    environment:
      - NODE_ENV=development
    depends_on:
      - finances_database
    volumes:
      - ./finances:/var/www/finances
    ports:
      - 3333:3333
    networks:
      - finances_network
    links:
      - finances_database:finances_database

  finances_webserver:
    image: nginx:latest
    # build: ./nginx
    container_name: finances_webserver
    depends_on:
      - finances_backend
    ports:
      - 80:80
    networks:
      - finances_network

networks:
  finances_network:
    driver: bridge

volumes:
  finances_database:
    driver: local
