version: '3.7'

services:
  finances_database:
    image: postgres:alpine
    container_name: finances_database
    environment:
      - POSTGRES_MULTIPLE_DATABASES=finances,finances_test
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
        - ./docker/database:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    networks:
      - finances_network

  finances_backend:
    build: ./docker/backend
    container_name: finances_backend
    environment:
      - NODE_ENV=development
    depends_on:
      - finances_database
    volumes:
      - ./finances:/var/www/finances
    ports:
      - 3333:3333
    networks:
      - finances_network
    links:
      - finances_database:finances_database

  finances_webserver:
    image: nginx:latest
    container_name: finances_webserver
    depends_on:
      - finances_backend
    ports:
      - 80:80
    networks:
      - finances_network

networks:
  finances_network:
    driver: bridge
